numpy is a linear algebra library for python

### numpy arrays

In [5]:
import numpy as np

In [6]:
my_list = [1, 2, 3, 4, 5]
print(my_list)


[1, 2, 3, 4, 5]


In [7]:

arr = np.array(my_list)
arr

array([1, 2, 3, 4, 5])

In [8]:
my_mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [9]:
my_mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.twos((3, 3))

AttributeError: module 'numpy' has no attribute 'twos'

In [ ]:
np.linspace(0,15,3)

array([ 0. ,  7.5, 15. ])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.random.rand(3,3)


array([[0.54006183, 0.19013097, 0.63866513],
       [0.7363498 , 0.11862043, 0.72619088],
       [0.24630747, 0.0395723 , 0.09274903]])

In [ ]:
np.random.rand()

0.8177844232303357

In [ ]:
import numpy as np
np.random.seed(42)

# Generate various random data
uniform_data = np.random.rand(100)
normal_data = np.random.randn(5,5)
integers = np.random.randint(1, 100, 50)
choices = np.random.choice(['A', 'B', 'C'], 20)
uniform_data
normal_data

array([[ 0.08704707, -0.29900735,  0.09176078, -1.98756891, -0.21967189],
       [ 0.35711257,  1.47789404, -0.51827022, -0.8084936 , -0.50175704],
       [ 0.91540212,  0.32875111, -0.5297602 ,  0.51326743,  0.09707755],
       [ 0.96864499, -0.70205309, -0.32766215, -0.39210815, -1.46351495],
       [ 0.29612028,  0.26105527,  0.00511346, -0.23458713, -1.41537074]])

In [ ]:
normal_data.reshape(25,1)

array([[ 0.08704707],
       [-0.29900735],
       [ 0.09176078],
       [-1.98756891],
       [-0.21967189],
       [ 0.35711257],
       [ 1.47789404],
       [-0.51827022],
       [-0.8084936 ],
       [-0.50175704],
       [ 0.91540212],
       [ 0.32875111],
       [-0.5297602 ],
       [ 0.51326743],
       [ 0.09707755],
       [ 0.96864499],
       [-0.70205309],
       [-0.32766215],
       [-0.39210815],
       [-1.46351495],
       [ 0.29612028],
       [ 0.26105527],
       [ 0.00511346],
       [-0.23458713],
       [-1.41537074]])

In [ ]:
normal_data.max()

np.float64(1.477894044741516)

In [ ]:
normal_data.shape

(5, 5)

In [ ]:
arr1 = np.arange(0,10)

In [ ]:
arr1


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr1[8]

np.int64(8)

In [ ]:
arr[1:4]

array([2, 3, 4])

In [ ]:
arr1[:6]

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr1

array([100, 499,   2,   3,   4,   5,   6,   7,   8,   9])

In [ ]:
arr2 = arr1.copy()

In [ ]:
arr2

array([100, 499,   2,   3,   4,   5,   6,   7,   8,   9])

In [ ]:
arr2[1]=600

In [ ]:
arr2[1]=1499
arr2

array([ 100, 1499,    2,    3,    4,    5,    6,    7,    8,    9])

##### this effects the original array as well because arr2 is just a view of arr1, not a copy. To create a copy, you can use the copy() method:

2d indexing in numpy array

In [ ]:
arr3 = np.arange(0,100)

In [ ]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
arr3.reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
x = arr3>49

In [ ]:
print(arr3[x])

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
 98 99]


numpy operations

array with array operartions<br>
array with scalars<br>
universal array functions

In [31]:
arr = np.arange(1,101)

In [32]:
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [33]:
arr = arr / arr

In [34]:
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [36]:
(arr+2)**2

array([9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9.,
       9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9.,
       9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9.,
       9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9.,
       9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9.,
       9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9.])

In [37]:
np.sqrt(arr)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [38]:
np.log(arr)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [39]:
np.sin(arr)

array([0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098,
       0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098,
       0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098,
       0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098,
       0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098,
       0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098,
       0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098,
       0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098,
       0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098,
       0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098,
       0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098,
       0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098,
       0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098,
       0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098,
       0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147

exercise

In [40]:
x  = np.zeros(10)

In [41]:
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [42]:
x = np.ones(10)

In [43]:
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [45]:
x = np.full(10, 5)

In [46]:
x

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [47]:
y = np.full(20,"a")

In [50]:
np.arange(1,51)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [59]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [60]:
import pandas as pd

In [63]:
l = ['a','b','c','d','e']
d = [1,2,3,4,5]
s = pd.Series(d,l)
s


a    1
b    2
c    3
d    4
e    5
dtype: int64

In [64]:
from numpy.random import randn

In [66]:
np.random.seed(101)

In [ ]:
df = pd.DataFrame()